
version: 2

sources:
    - name: raw
      schema: gz_raw_data
      description: raw data from GREENWEEZ company. That is a marketplace that sells eco & bio products
      tables:
        - name: products
          identifier: raw_gz_product
          description: table contains product_id & thepurcahse price 
          columns:
            - name: products_id
              description: the unique id for all the different products
              tests:
                - unique
                - not_null
            - name: purchase_price
              description: the total purchase price for a unique product id        
        - name: sales
          identifier: raw_gz_sales
          description: sales of Greenweez / we have one row per product_id found in each orders_id
          loaded_at_field: "CAST(date_date AS TIMESTAMP)"
          freshness:
            warn_after: {count: 90, period: day}
          columns:
            - name: date_date
              description: date of purchase
            - name: order_id
              description: The id code for each transaction
            - name: pdt_id
              description: The id code for each product
            - name: revenue
              description: the gain received for each tansaction & product
            - name: quantity
              description: the quantity demanded per order for a product
          tests:
           - unique:
               column_name: "(pdt_id || '-' || orders_id)"
        - name: ship
          identifier: raw_gz_ship
          description: shipping fees that would be mandatory to rightly calulate the margin
          columns:
            - name: order_id
              description: the unique code for each order recieved
            - name: shipping_fee
              description: The cost charged by a carrier to transport the product
            - name: logcost
              description: The cost associated with handling, storing, and tracking goods within a warehouse.
            - name: ship_cost
              description:  The total cost of transporting a product from origin to destination, including both shipping fees and log costs.
        - name: adwords
          identifier: raw_gz_adwords
          description: indicatiors from the adwords app to calculate traffic & others
          columns:
            - name: date_date
              description: the date every interactions happens on the site
            - name: paid_source
              description: the source of paiement
            - name: campaign_key
              description: the unique id for every campaign
            - name: camPGN_name
              description: the name of the campigns
              tests:
                  - not_null
            - name: ads_cost
              description: the amount paid for ads
            - name: impression
              description: the amount of times people view the site
            - name: click
              description: the amount of clicks people do on the site
          tests:
           - unique:
               column_name: "(date_date || '-' || campaign_key)"
        - name: bing
          identifier: raw_gz_bing
          description: indicatiors from the bing app to calculate traffic & others
          columns:
            - name: date_date
              description: the date every interactions happens on the site
            - name: paid_source
              description: the source of paiement
            - name: campaign_key
              description: the unique id for every campaign
            - name: camPGN_name
              description: the name of the campigns
              tests:
                  - not_null
            - name: ads_cost
              description: the amount paid for ads
            - name: impression
              description: the amount of times people view the site
            - name: click
              description: the amount of clicks people do on the site
          tests:
           - unique:
               column_name: "(date_date || '-' || campaign_key)"         
        - name: criteo
          identifier: raw_gz_criteo
          description: indicatiors from the criteo app to calculate traffic & others
          columns:
            - name: date_date
              description: the date every interactions happens on the site
            - name: paid_source
              description: the source of paiement
            - name: campaign_key
              description: the unique id for every campaign
            - name: camPGN_name
              description: the name of the campigns
              tests:
                - not_null
            - name: ads_cost
              description: the amount paid for ads
            - name: impression
              description: the amount of times people view the site
            - name: click
              description: the amount of clicks people do on the site 
          tests:
           - unique:
               column_name: "(date_date || '-' || campaign_key)"    
        - name: facebook
          identifier: raw_gz_facebook
          description: indicatiors from the facebook app to calculate traffic & others
          columns:
            - name: date_date
              description: the date every interactions happens on the site
            - name: paid_source
              description: the source of paiement
            - name: campaign_key
              description: the unique id for every campaign
            - name: camPGN_name
              description: the name of the campigns
              tests:
               - not_null
            - name: ads_cost
              description: the amount paid for ads
            - name: impression
              description: the amount of times people view the site
            - name: click
              description: the amount of clicks people do on the site
          tests:
           - unique:
               column_name: "(date_date || '-' || campaign_key)"                        
models:
  - name: int_sales_margin
    description: margin calculation per order
    columns:
      - name: orders_id
        description: orders key
        tests:
          - not_null
      - name: products_id
        description: products key
        tests:
          - not_null
      - name: margin
        description: Margin = Revenue - Purchase_cost
        tests:
          - not_null
      - name: Purchase_cost
        description: Purchase_cost = Quantity * Purchase_price
        tests:
          - not_null
      - name: date_date
        description: date of the order
        tests:
          - not_null
      - name: revenue
        description: sum of revenue per order
        tests:
          - not_null
      - name: quantity
        description: sum of quantity per order
        tests:
          - not_null

  - name: int_campaigns_day
    description: aggregating numerical value
    columns:
      - name: date_date
        description: date of interactions
        tests:
          - not_null
      - name: ads_cost
        description: sum of ads cost
        tests:
          - not_null
      - name: ads_impression
        description: sum of ads impressions
        tests:
          - not_null
      - name: ads_click
        description: sum of all clicks
        tests:
          - not_null

  - name: finance_campaigns_days
    description: joining the finance days tab and the campaigns days tab
    columns:
      - name: date_date
        description: date of interactions
        tests:
          - not_null
      - name: ads_cost
        description: sum of ads cost
        tests:
          - not_null
      - name: ads_impression
        description: sum of ads impressions
        tests:
          - not_null
      - name: ads_click
        description: sum of all clicks
        tests:
          - not_null
      - name: ads_margin
        description: op margin - ads cost
        tests:
          - not_null 
      - name: operational_margin
        description: something
        tests:
          - not_null
      - name: average_basket
        description: soemthnig
        tests:
          - not_null    
      - name: quantity
        description: qty
        tests:
          - not_null    
      - name: revenue
        description: all received
        tests:
          - not_null  
      - name: purchase_cost
        description: something
        tests:
          - not_null      
      - name: margin
        description: some
        tests:
          - not_null    
      - name: shipping_fee
        description: that thing
        tests:
          - not_null    
      - name: logcost
        description: transport 
        tests:
          - not_null    
      - name: ship_cost
        description: fare
        tests:
          - not_null    