
version: 2

sources:
    - name: raw
      schema: gz_raw_data
      description: raw data from GREENWEEZ company. That is a marketplace that sells eco & bio products
      tables:
        - name: products
          identifier: raw_gz_product
          description: table contains product_id & thepurcahse price 
          columns:
            - name: products_id
              description: the unique id for all the different products
              tests:
                - unique
                - not_null
            - name: purchase_price
              description: the total purchase price for a unique product id        
        - name: sales
          identifier: raw_gz_sales
          description: sales of Greenweez / we have one row per product_id found in each orders_id
          loaded_at_field: "CAST(date_date AS TIMESTAMP)"
          freshness:
            warn_after: {count: 90, period: day}
          columns:
            - name: date_date
              description: date of purchase
            - name: order_id
              description: The id code for each transaction
            - name: pdt_id
              description: The id code for each product
            - name: revenue
              description: the gain received for each tansaction & product
            - name: quantity
              description: the quantity demanded per order for a product
          tests:
           - unique:
               column_name: "(pdt_id || '-' || orders_id)"
        - name: ship
          identifier: raw_gz_ship
          description: shipping fees that would be mandatory to rightly calulate the margin
          columns:
            - name: order_id
              description: the unique code for each order recieved
            - name: shipping_fee
              description: The cost charged by a carrier to transport the product
            - name: logcost
              description: The cost associated with handling, storing, and tracking goods within a warehouse.
            - name: ship_cost
              description:  The total cost of transporting a product from origin to destination, including both shipping fees and log costs.
models:
   - name: int_sales_margin
     description: margin calculation per order
     columns:
       - name: orders_id
         description: orders key
         tests:
           - not_null
       - name: products_id
         description: products key
         tests:
           - not_null
       - name: margin
         description: Margin = Revenue - Purchase_cost
         tests:
           - not_null
       - name: Purchase_cost
         description: Purchase_cost = Quantity * Purchase_price
         tests:
           - not_null
       - name: date_date
         description: date of the order
         tests:
           - not_null
       - name: revenue
         description: sum of revenue per order
         tests:
           - not_null
       - name: quantity
         description: sum of quantity per order
         tests:
           - not_null
     tests:
       - unique:
           column_name: "(orders_id || '-' || products_id)"